### ISSUE TITLE
"AssertionError: Text is too short" during install

### ISSUE THREAD

**Issue by eporsche** [rhasspy/rhasspy-speech#2]
Something goes wrong when rhasspy speech tries to train the model. However I am not sure what.

```
INFO:root:Downloading https://huggingface.co/datasets/rhasspy/rhasspy-speech/resolve/main/models/en_US-rhasspy.tar.gz?download=true
INFO:root:Downloading Home Assistant entities from ws://supervisor/core/websocket
INFO:wyoming_rhasspy_speech.web_server:Training en_US-rhasspy (suffix=None)
ERROR:wyoming_rhasspy_speech.web_server:Unexpected error while training
Traceback (most recent call last):
  File "/usr/src/wyoming_rhasspy_speech/web_server.py", line 461, in train_model
    intents, words = get_intents(state, model_id, suffix)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/wyoming_rhasspy_speech/web_server.py", line 423, in get_intents
    return Intents.from_files(sentence_files), words
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/intents.py", line 291, in from_files
    return Intents.from_dict(intents_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/intents.py", line 368, in from_dict
    slot_lists={
               ^
  File "/usr/src/hassil/intents.py", line 369, in <dictcomp>
    list_name: _parse_list(list_name, list_dict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/intents.py", line 409, in _parse_list
    text_in=_maybe_parse_template(value["in"], allow_template),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/intents.py", line 461, in _maybe_parse_template
    return parse_sentence(text)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/parse_expression.py", line 213, in parse_sentence
    seq = parse_expression(chunk, metadata=metadata)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/parse_expression.py", line 163, in parse_expression
    return parse_group_or_alt_or_perm(chunk, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/parse_expression.py", line 99, in parse_group_or_alt_or_perm
    item = parse_expression(item_chunk, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/parse_expression.py", line 163, in parse_expression
    return parse_group_or_alt_or_perm(chunk, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/parse_expression.py", line 82, in parse_group_or_alt_or_perm
    seq_text = remove_delimiters(seq_chunk.text, GROUP_START, GROUP_END)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/hassil/parser.py", line 302, in remove_delimiters
    assert len(text) > 2, "Text is too short"
           ^^^^^^^^^^^^^
AssertionError: Text is too short

```

**Comment by eporsche** [comment]
the error boiled down to some of my exposed entities had a shorter name than 2 letters
